# wrangler.toml

name = "nocodb-elysia"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

routes = [{ pattern = "api.myk.rest", custom_domain = true }]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
